exports.getDummyProduction = async () => {
    return [
      {
        id: 1, // Tambahkan id supaya key React aman
        production_no: "251000023",
        status_po: "Closed",
        sales_order_no: "241000021",
        buyer_code: "CL00008",
        buyer_name: "KARYA SUTARINDO, PT",
        status_so: "Closed",
        so_cancel: true, // boolean
        checkin_no: "250004836",
        checkout_no: "250005011",
        doc_date: "2025-01-16",
        bulan: "January-2025",
        shift: "SHF-01",
        operator_name: "ALI KHAFIFUDIN",
        koordinator: "ALI KHAFIFUDIN",
        no_proses: 170,
        workcenter: "GRADING_FG_PANEL",
        kategori: "Plywood",
        item_code: "FGP00379",
        item_description: "FG PLYWOOD WBP 4X1220X2440",
        vol_per_pcs: 0.011907,
        mesin: "GRADING_FG",
        route: "PLYWOOD",
        workcenter2: "GRADING_FG_PANEL",
        status_check_out: "Open",
        input_pcs: 75,
        input_volume: 0.893,
        output_pcs: 24,
        output_volume: 0.2858,
        valid_qty_pcs: 19,
        valid_qty: 0.2263,
        reject_pcs: 5,
        reject_volume: 0.0595,
        unit_mesin: null,
      },
      {
        id: 2,
        production_no: "251000024",
        status_po: "Open",
        sales_order_no: "241000022",
        buyer_code: "CL00009",
        buyer_name: "INDO WOOD, PT",
        status_so: "Open",
        so_cancel: false,
        checkin_no: "250004837",
        checkout_no: "250005012",
        doc_date: "2025-01-17",
        bulan: "January-2025",
        shift: "SHF-02",
        operator_name: "BUDI SANTOSO",
        koordinator: "BUDI SANTOSO",
        no_proses: 171,
        workcenter: "SANDING",
        kategori: "Plywood",
        item_code: "FGP00380",
        item_description: "FG PLYWOOD MR 4X1220X2440",
        vol_per_pcs: 0.0125,
        mesin: "SANDING",
        route: "PLYWOOD",
        workcenter2: "SANDING_PANEL",
        status_check_out: "Open",
        input_pcs: 50,
        input_volume: 0.625,
        output_pcs: 45,
        output_volume: 0.5625,
        valid_qty_pcs: 40,
        valid_qty: 0.5,
        reject_pcs: 5,
        reject_volume: 0.0625,
        unit_mesin: "Unit-02",
      },
    ];
  };
  